### ISSUE TITLE
Criar Apresentacao 

### ISSUE THREAD

**Issue by brendonhps** [codenation-dev/squad-2-vhsys-1#5]
Criar apresentacao seguindo esse estilo: https://drive.google.com/file/d/1Owc4VYM492svCn7RlMnNs_Bk4ZGjZkvj/view

**Comment by amandabrbz** [comment]
https://docs.google.com/presentation/d/1f-Gqr7OE4ZE6XAO9IqkQgOt6mgmk93L10yGHXrEsaI0/edit?usp=sharing
